/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cikblr;

/**
 *
 * @author furka
 */
public class cikblr extends javax.swing.JFrame {

    /**
     * Creates new form cikblr
     */
    public cikblr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anapanel = new javax.swing.JPanel();
        xbut1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        aciklama_panel = new javax.swing.JPanel();
        xbut = new javax.swing.JLabel();
        btn3 = new javax.swing.JLabel();
        btn4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 150));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anapanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xbut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/error.png"))); // NOI18N
        xbut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xbut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xbut1MouseClicked(evt);
            }
        });
        anapanel.add(xbut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/circle.png"))); // NOI18N
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setMaximumSize(new java.awt.Dimension(24, 24));
        btn1.setMinimumSize(new java.awt.Dimension(24, 24));
        btn1.setPreferredSize(new java.awt.Dimension(24, 24));
        anapanel.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/circle-vol-1circle.png"))); // NOI18N
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        anapanel.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/1_1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 153, 173), 3));
        anapanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(anapanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        aciklama_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/error.png"))); // NOI18N
        xbut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        xbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xbutMouseClicked(evt);
            }
        });
        aciklama_panel.add(xbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/circle-vol-1circle.png"))); // NOI18N
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        aciklama_panel.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/circle.png"))); // NOI18N
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aciklama_panel.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_png/2_1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(116, 153, 173), 2));
        aciklama_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        getContentPane().add(aciklama_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        anapanel.setVisible(false);
        aciklama_panel.setVisible(true);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        aciklama_panel.setVisible(false);
        anapanel.setVisible(true);
    }//GEN-LAST:event_btn3MouseClicked

    private void xbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xbutMouseClicked

    private void xbut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbut1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_xbut1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cikblr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cikblr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cikblr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cikblr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cikblr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aciklama_panel;
    private javax.swing.JPanel anapanel;
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel xbut;
    private javax.swing.JLabel xbut1;
    // End of variables declaration//GEN-END:variables
}
